name: Merge any public branch to master
on:
  push:
    branches:
      - 'public/*'
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}

      - uses: actions/checkout@v3

      - name: merge branch
        run: |
          ssh -T git@github.com || echo "ssh -T git@github.com err"
          git config --list
          current_branch=$(git branch --show-current)
          repo=$(git remote get-url --push origin)
          repo="$(git remote get-url --push origin | sed -e 's#https://github.com/#git@github.com:#g' -e 's#/$##g').git"
          echo "repo: ${repo} current_branch: ${current_branch}"

          git remote set-url origin ${repo}
          git pull
          git checkout -b master origin/master --
          # git pull

          git config user.name "GitHub Actions"
          git config user.email "<>"
          echo "exec: git merge ${current_branch}"
          git status
          git diff
          git branch -a
          git merge ${current_branch} || echo "git merge ${current_branch} err"
          cat .github/workflows/auto-merge.yml
          git status
          git diff
          git push || echo "git push err"

          # git remote add public_repo $(echo ${repo} | sed 's/\.git/-public.git/g')
          # #git pull
          # #git fetch public_repo
          # git push --set-upstream public_repo ${current_branch} --force
