name: Merge any public branch to master
on:
  push:
    branches:
      - 'public/*'
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}
    
      - uses: actions/checkout@v3

      - name: merge branch
        run: |
          git status
          git pull
          git checkout -b master origin/master --
          git remote show origin
          echo "exec: git merge origin/$(git branch --show-current)"
          git merge origin/$(git branch --show-current)
          git remote set-url origin git@github.com:missuor/dev.git
          git push origin master
