name: Merge any public branch to master
on:
  push:
    branches:
      - 'public/*'
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}
    
      - uses: actions/checkout@v3

      - name: merge branch
        run: |
          current_branch=$(git branch --show-current)
          git pull
          git checkout -b master origin/master --
          git pull
          #git remote show origin
          echo "exec: git merge origin/${current_branch}"
          git merge --allow-unrelated-histories origin/${current_branch}
          git remote set-url origin git@github.com:missuor/dev.git
          git push origin master
