name: Merge any public branch to master
on:
  push:
    branches:
      - 'public/*'
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}

      - uses: actions/checkout@v3

      - name: merge branch
        run: |
          current_branch=$(git branch --show-current)
          repo=$(git remote get-url --push origin)
          echo "repo: ${repo} current_branch: ${current_branch}"
          repo=$(echo ${repo} | sed -e 's#https://github.com/#git@github.com:#g' -e 's#/$#.git#g')
          echo "repo: ${repo} current_branch: ${current_branch}"

          git remote set-url origin ${repo}
          git pull
          git checkout -b master origin/master --
          git pull
          
          git config user.name "GitHub Actions"
          git config user.email "<>"
          echo "exec: git merge origin/${current_branch}"
          git status
          git diff
          git merge ${current_branch} 2>/dev/null
          cat .github/workflows/auto-merge.yml
          git status
          git diff
          git push

          # git remote add public_repo $(echo ${repo} | sed 's/\.git/-public.git/g')
          # #git pull
          # #git fetch public_repo
          # git push --set-upstream public_repo ${current_branch} --force
