# .github/workflows/git-sync.yml

name: Git Sync

on:
  push:
    branches: ["public/*"]
  pull_request:
    branches: ["master"]

  schedule:
    # https://crontab.guru/every-2-hours
    # 周一到周五每30分钟一次
    - cron: "*/30 * * * 1-5"
    # 周六周日每8小时一次
    - cron: "0 */8 * * 0,6"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "missuor/dev-public"
          source_branch: "public/images"
          destination_repo: "missuor/dev"
          destination_branch: "public/images"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
